FROM python:3.11

RUN apt-get update && apt-get install -y \
    make build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    curl \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libffi-dev \
    liblzma-dev \
    git \
    vim \
    unixodbc-dev \
    unixodbc \
    libpq-dev \
    nano \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set up Docker Compose environment variables for mounting
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

# Set user and group IDs to match host machine
ARG USER_ID
ARG GROUP_ID

ARG USER_NAME
ARG USER_DISP_NAME
ARG USER_EMAIL

ENV UNAME=$USER_NAME
ENV UDNAME=$USER_DISP_NAME
ENV UEMAIL=$USER_EMAIL

WORKDIR /app

# Create a non-root user with the same UID and GID as the host user
RUN addgroup --gid $GROUP_ID appuser && \
    adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID appuser

# Change ownership of the working directory to the non-root user
ADD . ./

RUN chown -R appuser:appuser /app

RUN python -m pip install --upgrade pip
RUN pip install -r src/app/backend/requirements.txt

USER appuser

RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
RUN /bin/bash -c "source ~/.bashrc"

# Set up Git configuration
RUN git config --global user.name $UDNAME
RUN git config --global user.email $UEMAIL

EXPOSE 8000
EXPOSE 4000

CMD ["bash"]
